### PR TITLE
新增直播间信息接口

### PR DESCRIPTION
**Pull request by ATKghost**

### CODE REVIEW

**Comment by Passkou** [comment]
GET https://api.live.bilibili.com/room/v1/Room/get_info_by_id?ids=22544798

```json
{
  "code": 65530,
  "msg": "route_exception",
  "message": "route_exception",
  "data": {
    "excp_code": 0,
    "excp_msg": "Argument 1 passed to bl_room\\common\\domain_models\\room\\RoomService::fetchMultiRoomStatusInfoDeprecated() must be of the type array, string given, called in /data/app/room-service/frontend/controllers/v1/C_Room.php on line 120",
    "excp_class": "TypeError"
  }
}
```

**Comment by ATKghost** [comment]
要这样 
GET https://api.live.bilibili.com/room/v1/Room/get_info_by_id?ids[]=22544798
`{
    "code": 0,
    "msg": "success",
    "message": "success",
    "data": {
        "22544798": {
            "roomid": "22544798",
            "uid": "660303135",
            "uname": "Passkou",
            "verify": "",
            "virtual": "1",
            "cover": "https://i0.hdslb.com/bfs/live-key-frame/keyframe05282151000022544798lnt95g.jpg",
            "live_time": "0000-00-00 00:00:00",
            "round_status": "1",
            "on_flag": "0",
            "title": "半条命VR",
            "tags": "",
            "lock_status": "0000-00-00 00:00:00",
            "hidden_status": "0000-00-00 00:00:00",
            "user_cover": "https://i0.hdslb.com/bfs/live/new_room_cover/0472574e9bddf363cd3846f53b943c467d2bb58e.jpg",
            "short_id": "0",
            "online": "7",
            "area": "1",
            "area_v2_id": "235",
            "area_v2_parent_id": "6",
            "attentions": "0",
            "background": "",
            "room_silent": "0",
            "room_shield": "0",
            "try_time": "0000-00-00 00:00:00",
            "area_v2_name": "其他单机",
            "first_live_time": 1601022693,
            "live_id": 0,
            "live_status": 0
        }
    }
}`

**Comment by Passkou** [comment]
草，我以为那个 ids[] 是数组的意思。。

**Comment by Passkou** [comment]
但是和那个 API["info"]["room_info"] 接口差不多，感觉这个接口没什么用

**Comment by ATKghost** [comment]
很迷惑吧，刚试了下，多个id要这样加
https://api.live.bilibili.com/room/v1/Room/get_info_by_id?ids[]=22544798&ids[]=688323

**Comment by Passkou** [comment]
> 
> 
> 很迷惑吧，刚试了下，多个id要这样加
> [https://api.live.bilibili.com/room/v1/Room/get_info_by_id?ids[]=22544798&ids[]=688323](https://api.live.bilibili.com/room/v1/Room/get_info_by_id?ids%5B%5D=22544798&ids%5B%5D=688323)

好像没什么特别有用的信息，还是算了吧，https://github.com/Passkou/bilibili-api/blob/v5/bilibili_api/data/api/live.json#L3 这个就可以获取到这些信息

**Comment by ATKghost** [comment]
这个接口主要优点在于可以一次批量获取信息，带直播标题、封面、主播名称，节约请求次数。

**Comment by Passkou** [comment]
还是算了吧，相似功能的接口太多不太好，还是感谢你的贡献

**Pull request closed without merging**
